name: Build SonarCloud Staging
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
        SONAR_SCANNER_VERSION: 6.2.1.4610 # Find the latest version in the "macOS" link on this page:
                                        # https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Download and set up sonar-scanner
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux-x64.zip
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }} 
          echo "downloaded the scanner"
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          echo "unzipped the scanner"
      - name: Set up SonarScanner
        run: |
          echo "$HOME/.sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux-x64/bin" >> $GITHUB_PATH
          echo "Updated PATH:"
          cat $GITHUB_PATH
      - name: Print PATH for Debugging
        run: echo $PATH
      - name: Run sonar-scanner
        run: |
          sonar-scanner -Dsonar.host.url="${{ secrets.SONAR_SC_URL }}" -Dsonar.token="${{ env.SONAR_TOKEN }}" -Dsonar.verbose=true -Dsonar.organization=test-ping -Dsonar.projectKey=test-ping_test-ping-github-action-sc
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SC_TOKEN }} # Put the name of your token here
        
